"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Erika Chang, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

HMC2674
"""

def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    longest = 0
    for i in range(n):
        freq_list = [0] * 256
        #loops over each starting index with i
        for j in range(i, n): #i = start, j = end index, in range n
            substring = s[i: j + 1]
            for char in substring:
                string_char = ord(char)
                freq_list[string_char] += 1
            dupe = False
            for num in freq_list:
                if num > 1:
                    dupe = True
                    break
            if not dupe:
                current_len = j - i + 1
                if current_len > longest:
                    longest = current_len
            freq_list = [0] * 256
    return longest


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    longest = 0

    for i in range(n):
        freq_list = [0] * 256
        current_len = 0

        for j in range(i, n):
            current_char = ord(s[j])
            freq_list[current_char] += 1
      #if char repeating, resets
            if freq_list[current_char] > 1:
                while freq_list[current_char] > 1:
                    freq_list[ord(s[i])] -= 1
                    i += 1
            current_len = j - i + 1

            if current_len > longest:
                longest = current_len
    return longest


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    longest = 0
    start = 0 #index
    freq_list = [0] * 256

    for i in range(n):
        ascii_v = ord(s[i])
        #ascii of current iterating char

      #if the char is in substring, below code moves the window

        if freq_list[ascii_v] > 0: #if char inside window
            while freq_list[ascii_v] > 0: #moves the window so it restarts
                freq_list[ord(s[start])] -= 1
                start += 1
                #starting index moves forward

        freq_list[ascii_v] += 1

        current_len = i - start + 1
        if current_len > longest:
            longest = current_len

    return longest
